# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_errorMessage(object):
    def setupUi(self, errorMessage):
        errorMessage.setObjectName("errorMessage")
        errorMessage.setWindowModality(QtCore.Qt.ApplicationModal)
        errorMessage.resize(271, 127)
        self.centralwidget = QtWidgets.QWidget(errorMessage)
        self.centralwidget.setObjectName("centralwidget")
        self.errorLabel = QtWidgets.QLabel(self.centralwidget)
        self.errorLabel.setGeometry(QtCore.QRect(20, 20, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.errorLabel.setFont(font)
        self.errorLabel.setObjectName("errorLabel")
        errorMessage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(errorMessage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 271, 26))
        self.menubar.setObjectName("menubar")
        errorMessage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(errorMessage)
        self.statusbar.setObjectName("statusbar")
        errorMessage.setStatusBar(self.statusbar)

        self.retranslateUi(errorMessage)
        QtCore.QMetaObject.connectSlotsByName(errorMessage)

    def retranslateUi(self, errorMessage):
        _translate = QtCore.QCoreApplication.translate
        errorMessage.setWindowTitle(_translate("errorMessage", "Error"))
        self.errorLabel.setText(_translate("errorMessage", "Please input a number in all boxes."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    errorMessage = QtWidgets.QMainWindow()
    ui = Ui_errorMessage()
    ui.setupUi(errorMessage)
    errorMessage.show()
    sys.exit(app.exec_())
